# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-22 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toptran', '0005_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
