# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-22 15:26
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('toptran', '0009_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryChild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryFather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('categorychild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toptran.CategoryChild')),
                ('categoryfather', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toptran.CategoryFather')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to=settings.FILER_IMAGE_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='body'),
        ),
        migrations.AddField(
            model_name='categorychild',
            name='categorychild',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toptran.CategoryFather'),
        ),
    ]
