# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-23 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toptran', '0010_auto_20180622_2326'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryFather',
            new_name='Category',
        ),
        migrations.RemoveField(
            model_name='categorychild',
            name='categorychild',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='categoryfather',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='categorychild',
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='CategoryChild',
        ),
    ]
