# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-23 09:56
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toptran', '0011_auto_20180623_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
