# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-23 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toptran', '0015_category_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='available',
        ),
    ]
